### PR TITLE
Version Control and IDE set up

### PR DESCRIPTION
**Pull request by Motunodu**
I added about me.txt which contains a short description about me.

### CODE REVIEW

**Comment by djubreel** [comment]
Change the title from "this is about me" to the topic for this submission and also change your description from "Hello everyone ..." to what you added/removed.

**Comment by djubreel** [comment]
Attend to the comment above so your Pull request can be merged.

**Comment by Motunodu** [comment]
thank you. i have made the changes. hope it is correct now?

**Comment by Motunodu** [comment]
okay, i get it now. i have made the changes. Thank you

**Comment by djubreel** [comment]
Nice Job, Well done.

**Pull request merged**
