### PR TITLE
versionControl and IDE setup

### PR DESCRIPTION
**Pull request by damikanye**
a description about me
av a folder called versionContent then a text file named versioncontent.txt
the text file has a five line description about me

### CODE REVIEW

**Comment by damikanye** [comment]
pull request

**Comment by djubreel** [comment]
Well done. Can you change the title to the topic of the week, add a description and put your versionContent.txt file in a folder named version control . See a sample [here](https://github.com/Dufuna-Fem/Dufuna18/pull/7)

**Comment by damikanye** [comment]
Av done it can u pls check again

**Comment by djubreel** [comment]
The title is wrong and there's no description of what this pull request does or what changes you made. See a sample [here](https://github.com/Dufuna-Fem/Dufuna18/pull/7)

**Comment by damikanye** [comment]
pls check if its correct now

**Pull request merged**
