### PR TITLE
Version Control and IDE setup

### PR DESCRIPTION
**Pull request by Dinaka**
updated version

### CODE REVIEW

**Comment by djubreel** [comment]
Well done, But you need to change the title of your PR to the name of the topic for the week and add a better description. You can see a sample [here](https://github.com/Dufuna-Fem/Dufuna18/pull/7)

**Comment by Dinaka** [comment]
Good evening, please i need help to commit and push the renamed file
Thank you.

**Comment by Dinaka** [comment]
Its telling me file locked and can't commit. please help

**Comment by djubreel** [comment]
@Dinaka , Reach out to your mentor to assist with that.

**Pull request merged**
